### ISSUE TITLE
Create phone number component

### ISSUE THREAD

**Issue by dnaidionov** [cardstack/ui-components#20]
Phone number is an extension of text field, with predefined input restrictions, formatting, and validations

![image](https://user-images.githubusercontent.com/1836666/56830225-ce94f480-6833-11e9-9007-c9aae1385bdd.png)

- Phone number allows only digits
- When user starts entering phone number we should display mask for the remaining digits
- Phone number should include country code **(needs design)** 
- **OPTIONAL** When user finished entering phone number and blurs the control, we display confirmation (green message under the field). Confirmation is dismissed after the delay.

**Comment by dnaidionov** [comment]
@nicholas02261987 can you modify a wireframe to include the country code or country selection - whichever way you see more fitting.

**Comment by nicholas02261987** [comment]
we can include a drop down of countries for users to select. this can sit to the right or left of the number field and shorten the number field if needed.

Users should bee able to type into the country select field to to narrow down to their country.
