### ISSUE TITLE
Create Password component

### ISSUE THREAD

**Issue by dnaidionov** [cardstack/ui-components#26]
Password is an extension of textfield. 
By default the data in the password field is not shown as user types it (replaced by mask), but user can choose to display it. 
![image](https://user-images.githubusercontent.com/1836666/57385844-34ad4000-7181-11e9-995c-ba7896eda001.png)

When creating a password we should validate that password meets security requirements, and display validation error if it doesn't. 
When logging into account there would be no pre-submit validation

There are multiple other ways to unlock account, we start with password only. Other methods will be implemented later and separate tickets will address them.

### Password security options
Password security requirements should be configurable by developers. 
We will provide following options:
- minimum length (number)
- must include uppercase characters (boolean)
- must include lowercase characters (boolean)
- must include digits (boolean)
- must include special characters (list of characters)
- function (function that would be called to verify password validity - e.g. that would verify password history and block repeating passwords, or validate against known leaked password files, etc)

By default no options are selected.

**Comment by nicholas02261987** [comment]
Here is the design - it is listed as a passcode but can be called password if we want. The idea here is to provide many forms of unlocking an account and users can use more than one way or use them as combined ways - each can be saved as a card - like a key.

<img width="1593" alt="Screen Shot 2019-05-06 at 2 07 10 PM" src="https://user-images.githubusercontent.com/48684509/57245271-6b137f80-7008-11e9-9815-20f87d3d4f68.png">

Ideally users will use a CardStack Contact Cards to log into things - needs a better name!!

Here is a user flow and from for how users can create a CS account and in turn create a contact card.

![Artboard – 1](https://user-images.githubusercontent.com/48684509/57245378-bb8add00-7008-11e9-8672-b4baecbbcb21.png)

**Comment by dnaidionov** [comment]
I will split this into multiple issues - one for each of the unlocking methods. This ticket will continue to be dealing just with passcode.
