### ISSUE TITLE
Create generic Registration form

### ISSUE THREAD

**Issue by dnaidionov** [cardstack/ui-components#44]
Registration form consists of email, password, "I agree to T&C" checkbox, and Register CTA  UI components. 
Register button is disabled until email and password are validated and checkbox is checked.
When user enters email we should validate that email is in valid format and there's no existing account registered with that email. 
When user enters password we should validate that it complies with security requirements (TBD)

If validations pass, the Register button becomes enabled. 

![image](https://user-images.githubusercontent.com/1836666/57543330-1468b700-7322-11e9-8e72-5a4006776b12.png)

**Comment by bagby** [comment]
@dnaidionov we don't currently have a boolean Checkbox field, that will need to be added first.

**Comment by bagby** [comment]
Created #52
