### ISSUE TITLE
Bring in existing variables/components

### ISSUE THREAD

**Issue by jenweber** [cardstack/ui-components#5]
This PR has work by @burieberry has work that we can bring into this project:

https://github.com/cardstack/cardstack/pull/752

**Comment by burieberry** [comment]
This ticket can probably go on hold. It consists of refactoring work that's not directly relevant to the examples we're building in this repo.

**Comment by jenweber** [comment]
In that case, I think we should go ahead and close it. Feel free to re-open if you think it should stick around.
