### ISSUE TITLE
User should be able to add additional phone numbers, emails, addresses on the contact form

### ISSUE THREAD

**Issue by dnaidionov** [cardstack/ui-components#56]
User should be able to add additional contact info fields (phone/email/address)

![image](https://user-images.githubusercontent.com/1836666/57409979-97213300-71b7-11e9-987c-82ef8421d7ef.png)

---
@nicholas02261987 I think we need ability to designate one phone/email/address as primary if several are entered. What would be the best way to do it?

**Comment by nicholas02261987** [comment]
The first one entered should be primary, we can also add primary as a type
with work and home. Additionally, when a user drags a contact card to a
form, they can select what number they want the receiver to see. They can
also select the default number in the saved card. But adding primary here
is a good idea.

**Comment by bagby** [comment]
@dnaidionov The description of this story does not match the title, I thought this was about adding more text fields of a particular type (phone, email, address, etc). Can we separate them out into 2 stories?

For now I'll work on the story that the title describes (the little green + button to the right of the fields).

**Comment by dnaidionov** [comment]
@bagby moved contact type to #65
