### ISSUE TITLE
Add country selector to phone component and make mask dependent on country

### ISSUE THREAD

**Issue by dnaidionov** [cardstack/ui-components#57]
We should include country/country code selection in the phone number component. Phone number mask should depend on the country selected. 
By default select US.
We can utilize one of the existing libraries (preferably based on Google's `libphonenumber`) - e.g. https://github.com/Romanior/ember-intl-phone-input or https://qonto.github.io/ember-phone-input/.

**Comment by robustdj** [comment]
This is another good one: https://github.com/justin-lau/ember-intl-tel-input

**Comment by robustdj** [comment]
Hmm nvm, that one hasn't been updated since 2015
