### ISSUE TITLE
Create CTA component

### ISSUE THREAD

**Issue by robustdj** [cardstack/ui-components#6]
<img width="100%" alt="Screen Shot 2019-04-23 at 10 20 52 AM" src="https://user-images.githubusercontent.com/118005/56602074-85357280-65b1-11e9-9579-66c06991efa7.png">

Note that there is a primary and secondary CTA. When styling these, keep in mind the ability to make these theme-able later on. Use variables for the colors.

**Comment by burieberry** [comment]
I don't know if this is how we want to do it, but here's something I tried before to make a themeable button. `@label` determined the theme style changes.

```
<button
  class="dotbc-button dotbc-button--{{@label}}"
  data-test-dotbc-button
  ...attributes
>
  {{yield}}
</button>
```
