### ISSUE TITLE
Create textfield component

### ISSUE THREAD

**Issue by robustdj** [cardstack/ui-components#7]
![Screen Shot 2019-04-23 at 10 25 57 AM](https://user-images.githubusercontent.com/118005/56602395-39cf9400-65b2-11e9-99fa-505ffe7516e8.png)

A useful codepen that does the label/placeholder animation: https://codepen.io/nathanlong/pen/kkLKrL

**Comment by bagby** [comment]
There's also https://codepen.io/atunnecliffe/pen/gpKzQw, which is CSS-only (no JS).
